### PR TITLE
Add Email as a scalar to User

### PR DESCRIPTION
**Pull request by shanewilson**
**What kind of change does this PR introduce?**
Add Email as a scalar to User so we can add custom validation/resolvers etc like we will with Dates.

**Does this PR introduce a breaking change?**
No

**What needs to be documented once your changes are merged?**
describe expectations for scalar types when we start to add validation

### CODE REVIEW

**Comment by tazsingh** [comment]
I like the approach with making it a `scalar` 👍

In the past I've had `Email` as a full-blown `type` as it had a property of `verified` for every `email`. Users could also have multiple emails for an Account. I believe we have a similar consideration to have email verification in our system? If so, should we adopt a similar model of making it a `type`?

**Comment by shanewilson** [comment]
I don't have strong feelings either way - although I would say you could have the Email type and scalar, like: 

```
EmailType {
email: Email
verified: Boolean
primary: Boolean
}
```

for example

**Comment by shanewilson** [comment]
the scalar types work really well with mock data - rather than having to go like:

```
User {
email: faker.email()
}
Partner {
email: faker.email()
url: faker.url()
```

I can just do:

```
Email: () => faker.email()
URI: () => faker.url()
```

and it mocks them everywhere

**Comment by tazsingh** [comment]
Yeah I like that `type` 👍 

The challenge with migrating later is that we'd have to create a new field to reference the type. Right now the field could reference it directly.

I think it can go 2 ways:

1. Create an `Email` scalar and have all fields reference: `email: Email`. In the future, we could introduce the `EmailType` and define it as `emails: [EmailType!]!` where `email` can remain the primary email.

2. Go with `emails(emailPreferenceType: EmailPreferenceType = ALL): [EmailType!]!` now, where `EmailPreferenceType` is an enum of `PRIMARY` or `ALL`.

I think we can go with either. Maybe 1 as it doesn't conflict with 2 later due to the fields won't collide?

In which case, I think this PR is good to go 👍

**Pull request merged**
